name: Always up github action
run-name: Always up github action
on:
  schedule:
    - cron: '0/4 0,5-23 * * *'  # See https://crontab.guru/#/10_0,5-23_*_*_*
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      # - run: curl https://selit-backend.onrender.com/api/v1/ 
      - run: curl https://n8n-instance-vowt.onrender.com/
